### ISSUE TITLE
Add option for displaying NCR and UCN

### ISSUE THREAD

**Issue by abelcheung** [abelcheung/rifiuti2#5]
(Using character `é` for examples below)

It would be nice to allow displaying non-ASCII path in NCR (`&#xE9;`) in XML mode, and either hex (`\xE9`) or UCN (`\u00E9`) in tab-delimited mode, instead of just "File can't be displayed in foobar encoding".

This is a tracking task with subtasks below:
- [x] Some characters inside path need to be converted to XML entities #13 
- [x] XML presentation of invalid file names #14 
- [x] Allow partially displayable characters in INFO2 legacy paths #15 
- [x] More permissive handling of unicode path #16

**Comment by abelcheung** [comment]
All subtasks done.
